on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # 5 hours 50 minutes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Update and install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install ecdsa bech32 requests
          pip install mnemonic bip32 bit pycryptodome cryptography

      - name: Run get_balance.py with timeout
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
        run: python get_balance.py
